/* eslint-disable max-lines */
import { CellData, TableData } from '@lxt/angular-components/table';

export const AGGREGATIONS_DATA: TableData = {
  columns: [
    { field: 'lastName', isVisible: true, localizerKey: 'firstName' },
    { field: 'firstName', isVisible: true, localizerKey: 'lastName' },
    { field: 'email', isVisible: true, localizerKey: 'email' },
    { field: 'height', isVisible: true, localizerKey: 'height', cellDataType: CellData.NUMBER },
    { field: 'width', isVisible: true, localizerKey: 'width', cellDataType: CellData.NUMBER },
  ],
  rows: [
    {
      id: 1,
      firstName: 'John',
      lastName: 'Doe',
      email: 'john.doe@example.com',
      height: 175,
      width: 80,
    },
    {
      id: 2,
      firstName: 'Jane',
      lastName: 'Doe',
      email: 'jane.doe@example.com',
      height: 165,
      width: 60,
    },
    {
      id: 3,
      firstName: 'Michael',
      lastName: 'Smith',
      email: 'michael.smith@example.com',
      height: 180,
      width: 85,
    },
    {
      id: 4,
      firstName: 'Emily',
      lastName: 'Johnson',
      email: 'emily.johnson@example.com',
      height: 160,
      width: 55,
    },
    {
      id: 5,
      firstName: 'William',
      lastName: 'Brown',
      email: 'william.brown@example.com',
      height: 170,
      width: 75,
    },
    {
      id: 6,
      firstName: 'Emma',
      lastName: 'Martinez',
      email: 'emma.martinez@example.com',
      height: 163,
      width: 62,
    },
    {
      id: 7,
      firstName: 'James',
      lastName: 'Taylor',
      email: 'james.taylor@example.com',
      height: 178,
      width: 82,
    },
    {
      id: 8,
      firstName: 'Olivia',
      lastName: 'Anderson',
      email: 'olivia.anderson@example.com',
      height: 168,
      width: 68,
    },
    {
      id: 9,
      firstName: 'Benjamin',
      lastName: 'Thomas',
      email: 'benjamin.thomas@example.com',
      height: 172,
      width: 79,
    },
    {
      id: 10,
      firstName: 'Ava',
      lastName: 'Jackson',
      email: 'ava.jackson@example.com',
      height: 160,
      width: 57,
    },
    {
      id: 11,
      firstName: 'Alexander',
      lastName: 'White',
      email: 'alexander.white@example.com',
      height: 175,
      width: 72,
    },
    {
      id: 12,
      firstName: 'Mia',
      lastName: 'Harris',
      email: 'mia.harris@example.com',
      height: 166,
      width: 63,
    },
    {
      id: 13,
      firstName: 'Daniel',
      lastName: 'Martin',
      email: 'daniel.martin@example.com',
      height: 182,
      width: 88,
    },
    {
      id: 14,
      firstName: 'Sophia',
      lastName: 'Thompson',
      email: 'sophia.thompson@example.com',
      height: 158,
      width: 58,
    },
    {
      id: 15,
      firstName: 'Logan',
      lastName: 'Garcia',
      email: 'logan.garcia@example.com',
      height: 179,
      width: 81,
    },
    {
      id: 16,
      firstName: 'Isabella',
      lastName: 'Robinson',
      email: 'isabella.robinson@example.com',
      height: 167,
      width: 66,
    },
    {
      id: 17,
      firstName: 'Liam',
      lastName: 'Clark',
      email: 'liam.clark@example.com',
      height: 176,
      width: 73,
    },
    {
      id: 18,
      firstName: 'Charlotte',
      lastName: 'Lewis',
      email: 'charlotte.lewis@example.com',
      height: 162,
      width: 59,
    },
    {
      id: 19,
      firstName: 'Elijah',
      lastName: 'Walker',
      email: 'elijah.walker@example.com',
      height: 181,
      width: 84,
    },
    {
      id: 20,
      firstName: 'Amelia',
      lastName: 'Hall',
      email: 'amelia.hall@example.com',
      height: 163,
      width: 65,
    },
    {
      id: 21,
      firstName: 'Aiden',
      lastName: 'Young',
      email: 'aiden.young@example.com',
      height: 177,
      width: 76,
    },
    {
      id: 22,
      firstName: 'Harper',
      lastName: 'Allen',
      email: 'harper.allen@example.com',
      height: 164,
      width: 61,
    },
    {
      id: 23,
      firstName: 'Carter',
      lastName: 'Wright',
      email: 'carter.wright@example.com',
      height: 173,
      width: 70,
    },
    {
      id: 24,
      firstName: 'Evelyn',
      lastName: 'King',
      email: 'evelyn.king@example.com',
      height: 159,
      width: 64,
    },
    {
      id: 25,
      firstName: 'Jackson',
      lastName: 'Scott',
      email: 'jackson.scott@example.com',
      height: 174,
      width: 77,
    },
    {
      id: 26,
      firstName: 'Abigail',
      lastName: 'Baker',
      email: 'abigail.baker@example.com',
      height: 161,
      width: 67,
    },
    {
      id: 27,
      firstName: 'Mason',
      lastName: 'Adams',
      email: 'mason.adams@example.com',
      height: 180,
      width: 83,
    },
    {
      id: 28,
      firstName: 'Elizabeth',
      lastName: 'Nelson',
      email: 'elizabeth.nelson@example.com',
      height: 166,
      width: 69,
    },
    {
      id: 29,
      firstName: 'Sebastian',
      lastName: 'Hill',
      email: 'sebastian.hill@example.com',
      height: 178,
      width: 78,
    },
    {
      id: 30,
      firstName: 'Addison',
      lastName: 'Ramirez',
      email: 'addison.ramirez@example.com',
      height: 160,
      width: 58,
    },
    {
      id: 31,
      firstName: 'Lucas',
      lastName: 'Campbell',
      email: 'lucas.campbell@example.com',
      height: 181,
      width: 86,
    },
    {
      id: 32,
      firstName: 'Grace',
      lastName: 'Mitchell',
      email: 'grace.mitchell@example.com',
      height: 165,
      width: 71,
    },
    {
      id: 33,
      firstName: 'Ethan',
      lastName: 'Perez',
      email: 'ethan.perez@example.com',
      height: 176,
      width: 74,
    },
    {
      id: 34,
      firstName: 'Lily',
      lastName: 'Roberts',
      email: 'lily.roberts@example.com',
      height: 162,
      width: 68,
    },
    {
      id: 35,
      firstName: 'Alexander',
      lastName: 'Cook',
      email: 'alexander.cook@example.com',
      height: 179,
      width: 82,
    },
    {
      id: 36,
      firstName: 'Nora',
      lastName: 'Murphy',
      email: 'nora.murphy@example.com',
      height: 163,
      width: 60,
    },
    {
      id: 37,
      firstName: 'Henry',
      lastName: 'Gonzalez',
      email: 'henry.gonzalez@example.com',
      height: 177,
      width: 75,
    },
    {
      id: 38,
      firstName: 'Chloe',
      lastName: 'Torres',
      email: 'chloe.torres@example.com',
      height: 168,
      width: 69,
    },
    {
      id: 39,
      firstName: 'Owen',
      lastName: 'Peterson',
      email: 'owen.peterson@example.com',
      height: 173,
      width: 80,
    },
    {
      id: 40,
      firstName: 'Madison',
      lastName: 'Gray',
      email: 'madison.gray@example.com',
      height: 160,
      width: 62,
    },
    {
      id: 41,
      firstName: 'Levi',
      lastName: 'James',
      email: 'levi.james@example.com',
      height: 178,
      width: 79,
    },
    {
      id: 42,
      firstName: 'Hannah',
      lastName: 'Watson',
      email: 'hannah.watson@example.com',
      height: 166,
      width: 70,
    },
    {
      id: 43,
      firstName: 'Gabriel',
      lastName: 'Bennett',
      email: 'gabriel.bennett@example.com',
      height: 180,
      width: 84,
    },
    {
      id: 44,
      firstName: 'Avery',
      lastName: 'Russell',
      email: 'avery.russell@example.com',
      height: 164,
      width: 63,
    },
    {
      id: 45,
      firstName: 'Leah',
      lastName: 'Griffin',
      email: 'leah.griffin@example.com',
      height: 169,
      width: 67,
    },
    {
      id: 46,
      firstName: 'Wyatt',
      lastName: 'Diaz',
      email: 'wyatt.diaz@example.com',
      height: 175,
      width: 76,
    },
    {
      id: 47,
      firstName: 'Ella',
      lastName: 'Hayes',
      email: 'ella.hayes@example.com',
      height: 161,
      width: 65,
    },
    {
      id: 48,
      firstName: 'Ryan',
      lastName: 'Ford',
      email: 'ryan.ford@example.com',
      height: 172,
      width: 73,
    },
    {
      id: 49,
      firstName: 'Natalie',
      lastName: 'Long',
      email: 'natalie.long@example.com',
      height: 167,
      width: 71,
    },
    {
      id: 50,
      firstName: 'David',
      lastName: 'Parker',
      email: 'david.parker@example.com',
      height: 183,
      width: 87,
    },
  ],
};
