import { CellData, TableData } from '@lxt/angular-components/table';

export const CELLTYPES_DATA: TableData = {
  columns: [
    { field: 'text', isVisible: true, cellDataType: CellData.TEXT },
    { field: 'number', isVisible: true, cellDataType: CellData.NUMBER },
    { field: 'boolean', isVisible: true, cellDataType: CellData.BOOLEAN },
    { field: 'date', isVisible: true, cellDataType: CellData.DATE },
    { field: 'checkbox', isVisible: true, cellDataType: CellData.CHECKBOX },
    { field: 'ordinal', isVisible: true, cellDataType: CellData.ORDINAL_NUMBER },
    { field: 'status', isVisible: true, cellDataType: CellData.STATUS },
    { field: 'progress', isVisible: true, cellDataType: CellData.PROGRESS },
  ],
  rows: [
    {
      id: 1,
      number: 111,
      text: 'placeholder',
      boolean: true,
      date: new Date(2024, 1, 1),
      checkbox: true,
      ordinal: 5,
      status: 'ready',
      progress: 0,
    },
    {
      id: 2,
      number: 222,
      text: 'another placeholder',
      boolean: false,
      date: new Date(2024, 1, 2),
      checkbox: false,
      ordinal: 4,
      status: 'active',
      progress: 10,
    },
    {
      id: 3,
      number: 333,
      text: 'yet another placeholder',
      boolean: true,
      date: new Date(2024, 1, 3),
      checkbox: true,
      ordinal: 3,
      status: 'warning',
      progress: 20,
    },
    {
      id: 4,
      number: 444,
      text: 'still another placeholder',
      boolean: false,
      date: new Date(2024, 1, 4),
      checkbox: true,
      ordinal: 2,
      status: 'deactivated',
      progress: 30,
    },
    {
      id: 5,
      number: 555,
      text: 'placeholder #5',
      boolean: true,
      date: new Date(2024, 1, 5),
      checkbox: true,
      ordinal: 1,
      status: 'emergencyStop',
      progress: 40,
    },
    {
      id: 6,
      number: 666,
      text: 'placeholder #6',
      boolean: false,
      date: new Date(2024, 1, 6),
      checkbox: true,
      ordinal: 5,
      status: 'maintenance',
      progress: 50,
    },
    {
      id: 7,
      number: 777,
      text: 'placeholder #7',
      boolean: true,
      date: new Date(2024, 1, 7),
      checkbox: false,
      ordinal: 4,
      status: 'jam',
      progress: 75,
    },
    {
      id: 8,
      number: 888,
      text: 'placeholder #8',
      boolean: false,
      date: new Date(2024, 1, 8),
      checkbox: true,
      ordinal: 3,
      status: 'error',
      progress: 95,
    },
    {
      id: 9,
      number: 999,
      text: 'placeholder #9',
      boolean: true,
      date: new Date(2024, 1, 9),
      checkbox: true,
      ordinal: 2,
      status: 'unknown',
      progress: 100,
    },
  ],
};
